# Generated by Django 4.0 on 2021-12-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangridApp', '0002_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='id',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='_id',
            field=models.AutoField(default=1, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
