"""
Django settings for djangrid project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
SITE_ROOT = os.path.dirname(os.path.realpath(__file__))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w&#c^zkf_pf&4lf&gk_bli%)2n7*zt1*+(_m_ia$q@&+@ry(i8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django.contrib.sites',
    'sorl.thumbnail',
    'tinymce',
    'django_extensions',
    
    'advanced_filters',

    'djangridApp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangrid.urls'


# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_DIR =os.path.join(SITE_ROOT,'templates')
# print ("TEMPLATE_DIR:", TEMPLATE_DIR)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'APP_DIRS': True,
        'DIRS': [TEMPLATE_DIR,],
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangrid.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

# STATIC_URL = 'static/'
STATIC_URL = '/static/'

# Static root is used for production
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = (
  os.path.join(SITE_ROOT, 'static/'),
)

# STATICFILES_DIRS = [
#     ('global', os.path.join(BASE_DIR, 'static')),
# ]

MEDIA_URL = 'uploaded_newsletters/'
# MEDIA_URL = '/images/'

# STATICFILES_DIRS = [
#     BASE_DIR / 'static',
#     # BASE_DIR / 'frontend/build/static'
# ]

# MEDIA_ROOT = BASE_DIR / 'static/images'
# STATIC_ROOT = BASE_DIR / 'staticfiles'


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


FROM_EMAIL = 'saran@zenstrabiohealth.com'
SENDER_NAME = 'Saran (Zenstra)'
MAIL_FROM = f'{SENDER_NAME} <{FROM_EMAIL}>'
REPLY_TO = 'suppport@zenstrabiohealth.com'
# REPLY_TO = 'saran@zenstrabiohealth.com'
load_dotenv('./sendgrid.env')
SENDGRID_API_KEY = os.environ.get('SENDGRID_API_KEY')
# print (SENDGRID_API_KEY)

EMAIL_BACKEND = "sendgrid_backend.SendgridBackend"
EMAIL_FILE_PATH = os.path.join(BASE_DIR,'email_output')
# print ("EMAIL_FILE_PATH:", EMAIL_FILE_PATH)

# Sendgrid-v5 settings
SENDGRID_SANDBOX_MODE_IN_DEBUG = False  # in debug mode, set to True so emails will not be delivered
SENDGRID_ECHO_TO_STDOUT = True
SENDGRID_TRACK_EMAIL_OPENS = True
SENDGRID_TRACK_CLICKS_HTML = True
SENDGRID_TRACK_CLICKS_PLAIN = True

# NEWSLETTER_RICHTEXT_WIDGET = "tinymce.widgets.TinyMCE"

# Django-Newsletter settings
# NEWSLETTER_CONFIRM_EMAIL = False
NEWSLETTER_CONFIRM_EMAIL_SUBSCRIBE = False  # True
NEWSLETTER_CONFIRM_EMAIL_UNSUBSCRIBE = False
NEWSLETTER_THUMBNAIL = 'sorl-thumbnail'
# NEWSLETTER_THUMBNAIL = 'easy-thumbnails'
NEWSLETTER_RICHTEXT_WIDGET = "tinymce.widgets.TinyMCE"
SITE_ID = 1
# # Amount of seconds to wait between each email. Here 100ms is used.
# NEWSLETTER_EMAIL_DELAY = 0.1
# # Amount of seconds to wait between each batch. Here one minute is used.
# NEWSLETTER_BATCH_DELAY = 60
# # Number of emails in one batch
# NEWSLETTER_BATCH_SIZE = 100

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"